### ISSUE TITLE
Explore definition of effective amount

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/spec#17]
reposting from Slack:

Going back to the discussing around effective amount (https://github.com/lbryio/lbrycrd/issues/203), do we want to consider only effective amounts for claims that are active, or all claims? I really don't see the use case for considering it for only active ones (assuming you are already taking into account any activation delay) especially when it relates to the new discovery tools we have in the app (i.e. sorting something by Top bids -  I don't care if the claim is in takeover or not) . The spec does say it's supposed to be 0 when a claim is not active. 

On a side note, the implementation also doesn't match the spec if I post a claim to lbry://one today for 1 LBC..that claim should be active right away because a takeover can't happen (If the stake is an update to an active claim, is the only accepted non-abandoned claim for a name, or does not cause a change in which claim is controlling the name, the activation delay is 0 (i.e. the stake becomes active immediately).) but we set the takeover height/effective amount to 0.  If effective amount isn't the right term in this case, we should reconsider it.

**Comment by lyoshenka** [comment]
can i close this? afaik the spec describes the behavior that we want. if lbrycrd does it differently, then we should eventually update lbrycrd to match the spec. do you agree?

**Comment by tzarebczan** [comment]
I guess this is okay now that we have pending effective amount, but this part still may be accurate - why set effective amount to 0 if there's no takeover going to happen?

I'll confirm : 

the implementation also doesn't match the spec if I post a claim to lbry://one today for 1 LBC..that claim should be active right away because a takeover can't happen (If the stake is an update to an active claim, is the only accepted non-abandoned claim for a name, or does not cause a change in which claim is controlling the name, the activation delay is 0 (i.e. the stake becomes active immediately).) but we set the takeover height/effective amount to 0.

**Comment by lyoshenka** [comment]
The spec does not say that the effective amount should be set to 0 during a takeover. According to my reading of the spec, the only way to get effective amount to 0 after a claim is active is to abandon it. If you read it differently or its not clear, I'm happy to update that. Otherwise, the set-to-0 behavior should be fixed in lbrycrd at some point.

**Comment by lyoshenka** [comment]
I can file that issue in lbycrd repo

**Comment by lyoshenka** [comment]
we decided to add a flag to wallet servers for an experimental new number that's like effective_amount except:
- its not affected by activation delay
- includes supports for content claims in the channel's total

https://github.com/lbryio/lbry-sdk/issues/3072

**Comment by lyoshenka** [comment]
updating the above: we're gonna call it `staked_amount`. no flag, it will just be there in sdk
