### ISSUE TITLE
Many dead links off the spec.

### ISSUE THREAD

**Issue by bitcoinbrisbane** [lbryio/spec#22]
https://lbry.tech/spec?_ga=2.13516727.1296393475.1587778860-519824460.1581147894 has many dead links.

- https://github.com/lbryio/lbrycrd/blob/master/src/chainparams.cpp
- https://github.com/lbryio/lbrycrd/blob/master/src/main.cpp#L1594
- https://github.com/lbryio/lbrycrd/blob/master/src/hash.cpp#L18

**Comment by kauffj** [comment]
@lyoshenka can you fix these? Or just remove source code links if not relevant

**Comment by kauffj** [comment]
Appreciate the report @bitcoinbrisbane!

**Comment by bitcoinbrisbane** [comment]
@kauffj no worries Jeremy.  Im reading through the docs to get up to speed on the project, and then hopefully make some PRs :smiley:
