### ISSUE TITLE
add google analytics tag to spec

### ISSUE THREAD

**Issue by finer9** [lbryio/spec#4]
I'm not sure how to add the GA tag since this is markdown.

Here is the new ID for spec.lbry.io:

UA-60403362-10

Here is the full tag for reference

<script async src="https://www.googletagmanager.com/gtag/js?id=UA-60403362-10"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-60403362-10');
</script>

**Comment by kauffj** [comment]
This will not actually launch at this URL, it'll end up becoming part of lbry.tech.
